### ISSUE TITLE
Datetimepicker not working

### ISSUE THREAD

**Issue by adamkudrna** [visionappscz/bootstrap-ui#83]
In the docs, Datetimepicker component does not work and outputs the following in console:

![datetimepicker](https://cloud.githubusercontent.com/assets/5614085/17302779/19e65cfe-581e-11e6-8c39-b72e19c0fcdc.png)

Error appears both on Forms and JavaScripts pages.

Environment: latest Chrome/OS X, latest Bower components.

**Comment by adamkudrna** [comment]
Version 2.2.1 is OK, see the docs on production (1 version behind repository): http://docs.bootstrap-ui.com/section-4.html

**Comment by crishpeen** [comment]
> **.size()**
> Returns: Integer
> version deprecated: 1.8, 
> removed: 3.0
sauce: https://api.jquery.com/size/

size() is removed in jQuery v3, should use length instead. And BUI uses jQuery v3 since updated to [twbs/bootstrap](https://github.com/twbs/bootstrap) v3.3.7.

Also [Eonasdan/bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) had latest release almost one year ago, so I don't expect them to fix this bug (there are also over 270 open issues). 

Suggested solutions are:

- temporary solution - downgrade to bootstrap v3.3.6
- switch to another datetimepicker
- fork [Eonasdan/bootstrap-datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) and update it to jQuery v3

**Comment by mbohal** [comment]
I think we should downgrade for now and start looking for a new datetimepicker. I do not believe that VisionApps has the resources to maintain a datetimepicker component. Im assigning the issue to @adamkudrna as he has the most insight about what it entails to downgrde the bootstrap dependency.

**Comment by ksxio** [comment]
And what about force usage of jQuery v2? Because Bootstrap v3.3.7 just added support of jQuery v3, not forcing to use it.

As far as I know (and using Bootstrap UI in latest version), I just forced in my bower.json usage of jQuery v2 and everything is working well.

**Comment by adamkudrna** [comment]
Let's start looking for a new date/time picker: #85
